'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navbar
    'nav.builders': 'Desarrolladoras',
    'nav.empresas': 'Empresas',
    'nav.blockchains': 'Blockchains',
    'nav.recursos': 'Recursos',
    'nav.join': 'Iniciar Sesión',
    'nav.dashboard': 'Dashboard',

    // Hero Section
    "hero.title": "Conectamos desarrolladoras, empresas, blockchains y protocolos para impulsar el futuro Web3 en LATAM",
    "hero.subtitle": "Buen día Builders es el lugar donde desarrolladoras construyen el ecosistema Web3 más vibrante de Latinoamérica.",
    "hero.builder.title": "Soy creadora",
    "hero.builder.subtitle": "Empieza tu camino Web3",
    "hero.company.title": "Soy empresa",
    "hero.company.subtitle": "Encuentra talento Web3",
    "hero.blockchain.title": "Soy blockchain",
    "hero.blockchain.subtitle": "Haz crecer tu protocolo con BdB",

    // Metrics
    'metrics.builders': 'Builders Activos en el Sistema',
    'metrics.companies': 'Empresas Vinculadas',
    'metrics.growth': 'Crecimiento anual de Graduados entre 2023',
    'metrics.funding': 'Nuevos Activos como Asset Crypto',

    // Main Sections
    'builders.title': 'Conectamos builders con ideas y oportunidades',
    'builders.description': 'Desde una educación especializada, pasamos al ecosistema donde tu futuro profesional puede crecer, aprender y conectarse con las mejores oportunidades.',
    'builders.cta': 'Quiero ser Builder',
    'companies.title': 'El talento Web3 que tu empresa necesita',
    'companies.description': 'Reclutamiento especializado, capacitación y consultoría estratégica para acelerar la transformación Web3 de tu organización.',
    'companies.cta': 'Contratar talento',
    'blockchains.title': 'Acelera la adopción de tu protocolo en LATAM',
    'blockchains.description': 'Educación técnica, onboarding y community building para expandir tu ecosistema en la región más prometedora.',
    'blockchains.cta': 'Expandir protocolo',

    // Builders Page
    'builders.page.badge': 'Postulaciones Cerradas',
    'builders.page.title': 'Código Futura 2025',
    'builders.page.subtitle': 'Las postulaciones para esta edición han cerrado exitosamente.',
    'builders.page.thanks': '¡Gracias a todas las programadoras que aplicaron! El programa está en marcha con builders increíbles transformándose de Web2 a Web3.',
    'builders.stats.title': 'Código Futura 2025 en números',
    'builders.stats.subtitle': 'El impacto de nuestra primera edición',
    'builders.stats.applications': 'Aplicaciones recibidas',
    'builders.stats.weeks': 'Semanas de formación',
    'builders.stats.free': 'Gratuito',
    'builders.stats.scholarships': 'Becas Builder Retreat',
    'builders.journey.title': 'El viaje de las builders',
    'builders.journey.subtitle': 'Un proceso estructurado de transformación de Web2 a Web3',
    'builders.journey.application': 'Aplicación',
    'builders.journey.application.title': 'Completa tu perfil',
    'builders.journey.application.desc': 'Formulario con tus datos y redes sociales',
    'builders.journey.application.duration': '10 min',
    'builders.journey.application.dates': 'Cerrado',
    'builders.journey.selection': 'Selección',
    'builders.journey.selection.title': 'Selección técnica',
    'builders.journey.selection.desc': 'Revisión de github y/o portfolio',
    'builders.journey.selection.duration': '1 semana',
    'builders.journey.selection.dates': 'Octubre',
    'builders.journey.program': 'Programa principal',
    'builders.journey.program.title': 'Código Futura (online, sincrónico)',
    'builders.journey.program.desc': 'Clases martes y jueves 18:30-20:00 + sábados de refuerzo. Labs y proyectos prácticos en Web3',
    'builders.journey.program.duration': '7 semanas',
    'builders.journey.program.dates': '7 Oct - 13 Nov',
    'builders.journey.retreat': 'Builder Retreat',
    'builders.journey.retreat.title': 'Casa Builder (con beca, presencial)',
    'builders.journey.retreat.desc': 'Experiencia inmersiva exclusiva para 20 builders seleccionadas que van a viajar a Buenos Aires, Argentina',
    'builders.journey.retreat.duration': '1 semana',
    'builders.journey.retreat.dates': '16-23 Nov',
    'builders.journey.bootcamp': 'Bootcamp Presencial',
    'builders.journey.bootcamp.title': 'Bootcamp intensivo (opcional y presencial)',
    'builders.journey.bootcamp.desc': 'Sesiones presenciales avanzadas y networking en Buenos Aires, Argentina',
    'builders.journey.bootcamp.duration': '3 días',
    'builders.journey.bootcamp.dates': '17-19 Nov',
    'builders.journey.hackathon': 'Hackathon',
    'builders.journey.hackathon.title': 'Hackathon Stellar (obligatorio y presencial)',
    'builders.journey.hackathon.desc': 'Construye tu proyecto final y demuestra todo lo aprendido',
    'builders.journey.hackathon.duration': '3 días',
    'builders.journey.hackathon.dates': '20-22 Nov',
    'builders.journey.graduation': 'Graduación',
    'builders.journey.graduation.title': 'Certificación y Portfolio',
    'builders.journey.graduation.desc': 'Certificación oficial y acompañamiento continuo',
    'builders.journey.graduation.duration': 'Lifetime',
    'builders.journey.graduation.dates': 'Nov 2025',
    'builders.journey.duration.label': 'Duración:',
    'builders.social.title': '¡Seguinos en nuestras redes!',
    'builders.social.subtitle': 'Mantente al día con el progreso del programa actual y entérate de futuras convocatorias',
    'builders.social.description': 'Conecta con nuestra comunidad de builders y sé parte de la transformación Web3',
    'builders.future.title': '¿Futuras ediciones?',
    'builders.future.description': 'Estamos evaluando próximas convocatorias. Mientras tanto, síguenos en redes sociales para no perderte ninguna novedad.',
    'builders.future.announcement': 'Anunciaremos nuevas fechas en nuestras redes sociales',
    'builders.faq.title': 'Preguntas Frecuentes',
    'builders.faq.subtitle': 'Respuestas sobre el programa y futuras ediciones',
    'builders.faq.q1': '¿Habrá otra edición del programa?',
    'builders.faq.a1': 'Estamos evaluando futuras ediciones. Mantente atenta a nuestras redes sociales para enterarte de novedades y próximas convocatorias.',
    'builders.faq.q2': '¿Fue realmente gratis este programa?',
    'builders.faq.a2': 'Sí, nuestro programa de formación es completamente gratuito para builders. Nos financiamos a través de servicios B2B con empresas y protocolos.',
    'builders.faq.q3': '¿Qué nivel técnico se necesitaba?',
    'builders.faq.a3': 'Buscábamos programadoras con experiencia en desarrollo. No se necesitaba conocimiento previo en Web3, eso se enseñaba durante el programa.',
    'builders.faq.q4': '¿Cómo fue el horario de las clases?',
    'builders.faq.a4': 'Las clases fueron martes y jueves de 18:30 a 20:00, más sábados de refuerzo durante 7 semanas (del 7 de octubre al 13 de noviembre). El hackathon final del 20-22 de noviembre es obligatorio y presencial.',
    'builders.faq.q5': '¿Qué es el Builder Retreat del 16-23 de noviembre?',
    'builders.faq.a5': 'Es una experiencia inmersiva de una semana para 20 builders seleccionadas con beca que viajaran a Buenos Aires, Argentina. Incluye el bootcamp presencial (17-19 nov) y networking exclusivo.',
    'builders.faq.q6': '¿Cómo puedo estar al tanto de próximas ediciones?',
    'builders.faq.a6': 'Síguenos en nuestras redes sociales (Twitter/X, LinkedIn e Instagram) donde anunciamos todas las novedades, convocatorias y actualizaciones del programa.',

    // Companies Page
    'companies.page.badge': 'Para Empresas',
    'companies.page.title': 'El talento Web3 que tu empresa necesita',
    'companies.page.subtitle': 'Reclutamiento especializado, capacitación y consultoría estratégica para acelerar la transformación Web3 de tu organización',
    'companies.page.cta': 'Agendar una llamada de descubrimiento',
    'companies.process.title': 'Nuestro proceso',
    'companies.process.subtitle': 'Metodología probada para delivery exitoso de proyectos Web3 corporativos',
    'companies.process.discovery': 'Discovery Call',
    'companies.process.discovery.desc': 'Entendemos tus necesidades específicas y contexto empresarial',
    'companies.process.discovery.duration': '1 hora',
    'companies.process.discovery.deliverable': 'Diagnóstico inicial',
    'companies.process.proposal': 'Propuesta Customizada',
    'companies.process.proposal.desc': 'Diseñamos plan específico con timeline y pricing transparente',
    'companies.process.proposal.duration': '3-5 días',
    'companies.process.proposal.deliverable': 'Proposal detallada',
    'companies.process.execution': 'Ejecución',
    'companies.process.execution.desc': 'Delivery con métricas claras y comunicación constante',
    'companies.process.execution.duration': 'Variable',
    'companies.process.execution.deliverable': 'Reportes semanales',
    'companies.process.followup': 'Follow-up',
    'companies.process.followup.desc': 'Soporte continuo y optimización basada en resultados',
    'companies.process.followup.duration': 'Ongoing',
    'companies.process.followup.deliverable': 'Success metrics',
    'companies.talent.title': 'Talentos',
    'companies.talent.subtitle': 'Perfiles disponibles según la necesidad de tu empresa',
    'companies.talent.junior': 'Junior Builders',
    'companies.talent.junior.desc': 'Alta motivación, formación reciente',
    'companies.talent.mid': 'Nivel-Medio',
    'companies.talent.mid.desc': 'Proyectos reales, experiencia práctica',
    'companies.talent.senior': 'Senior',
    'companies.talent.senior.desc': 'Capacidad de liderazgo, decisiones de arquitectura, mentoría',
    'companies.talent.specialist': 'Especialistas',
    'companies.talent.specialist.desc': 'Experiencia específica en verticales como DeFi, Gaming, Infraestructura',
    'companies.form.title': 'Comencemos a trabajar',
    'companies.form.subtitle': 'Cuéntanos tus necesidades y te contactaremos en 24 horas',
    'companies.form.company': 'Empresa',
    'companies.form.company.placeholder': 'Nombre de tu empresa',
    'companies.form.name': 'Tu nombre',
    'companies.form.name.placeholder': 'Tu nombre completo',
    'companies.form.email': 'Email corporativo',
    'companies.form.email.placeholder': 'tu@empresa.com',
    'companies.form.role': 'Tu rol',
    'companies.form.role.placeholder': 'CTO, HR Director, etc.',
    'companies.form.needs': '¿Qué necesitas?',
    'companies.form.needs.placeholder': 'Describe tu necesidad: hiring, training, consulting...',
    'companies.form.submit': 'Solicitar llamada de descubrimiento',
    'companies.form.submitting': 'Enviando...',

    // Blockchains Page
    'blockchains.page.badge': 'Para Blockchains y Protocolos',
    'blockchains.page.title': 'Acelera la adopción de tu protocolo en LATAM',
    'blockchains.page.subtitle': 'Educación técnica, incorporación y desarrollo de comunidad para expandir tu ecosistema en la región más prometedora',
    'blockchains.page.cta': 'Explorar nuestras alianzas',
    'blockchains.methodology.title': 'Nuestro enfoque',
    'blockchains.methodology.subtitle': 'Metodología de 4 fases para garantizar el éxito de tu expansión',
    'blockchains.methodology.phase': 'Fase',
    'blockchains.methodology.analysis': 'Análisis profundo del protocolo',
    'blockchains.methodology.analysis.desc': 'Entendemos tu grupo de aplicaciones, tokenomics y hoja de ruta.',
    'blockchains.methodology.analysis.duration': '2 semanas',
    'blockchains.methodology.analysis.deliverable': 'Análisis técnico',
    'blockchains.methodology.curriculum': 'Curriculum Design',
    'blockchains.methodology.curriculum.desc': 'Programa educativo customizado para tu protocolo',
    'blockchains.methodology.curriculum.duration': '3 semanas',
    'blockchains.methodology.curriculum.deliverable': 'Custom curriculum',
    'blockchains.methodology.execution': 'Execution & Delivery',
    'blockchains.methodology.execution.desc': 'Training delivery + community building execution',
    'blockchains.methodology.execution.duration': '12-24 semanas',
    'blockchains.methodology.execution.deliverable': 'Trained developers',
    'blockchains.methodology.metrics': 'Metrics & Optimization',
    'blockchains.methodology.metrics.desc': 'KPIs tracking y optimización continua',
    'blockchains.methodology.metrics.duration': 'Ongoing',
    'blockchains.methodology.metrics.deliverable': 'Performance reports',
    'blockchains.protocols.title': 'Protocolos en que desarrollamos',
    'blockchains.protocols.subtitle': 'Experiencia técnica en diferentes verticales del ecosistema Web3',
    'blockchains.form.title': 'Exploremos nuestra alianza',
    'blockchains.form.subtitle': 'Cuéntanos sobre tu protocolo y objetivos en LATAM',
    'blockchains.form.protocol': 'Protocolo/Proyecto',
    'blockchains.form.protocol.placeholder': 'Nombre de tu protocolo',
    'blockchains.form.name': 'Tu nombre',
    'blockchains.form.name.placeholder': 'Tu nombre completo',
    'blockchains.form.email': 'Email',
    'blockchains.form.email.placeholder': 'tu@protocolo.com',
    'blockchains.form.role': 'Tu rol',
    'blockchains.form.role.placeholder': 'DevRel, BD, etc.',
    'blockchains.form.goals': 'Objetivos en LATAM',
    'blockchains.form.goals.placeholder': '¿Qué buscas lograr en la región? Developer adoption, community growth, partnerships...',
    'blockchains.form.budget': 'Budget aproximado (USD)',
    'blockchains.form.budget.placeholder': 'Rango de investment para el programa',
    'blockchains.form.submit': 'Solicitar programa customizado',
    'blockchains.form.submitting': 'Enviando...',

    // Cities Section
    'cities.title': 'Buen día Builders en tu ciudad',
    'cities.subtitle': 'Expandiendo el ecosistema Web3 por toda Latinoamérica, ciudad por ciudad',
    'cities.operating': 'Ciudades donde operamos',
    'cities.active': 'Activo',
    'cities.coming': 'Próximamente',
    'cities.form.title': '¿Tu ciudad no está en la lista?',
    'cities.form.description': 'Regístrate y te contactaremos cuando Buen día Builders llegue a tu ciudad',
    'cities.form.email.placeholder': 'tu@email.com',
    'cities.form.city.placeholder': 'Tu ciudad',
    'cities.form.submit': 'Notificarme cuando esté disponible',
    'cities.form.disclaimer': 'Te mantendremos informado sobre eventos y oportunidades en tu región',

    // Footer
    'footer.newsletter.title': 'Para ponerse al día',
    'footer.newsletter.description': 'Recibe las últimas novedades del ecosistema Web3 en LATAM',
    'footer.newsletter.placeholder': 'tu@email.com',
    'footer.community.title': 'Comunidad',
    'footer.community.email': 'Enviar mensaje',
    'footer.community.email.desc': 'Contáctanos por correo',
    'footer.community.linkedin.desc': 'Conecta con nuestra red profesional',
    'footer.community.telegram.desc': 'Participa en nuestras conversaciones',
    'footer.community.discord.desc': 'Únete a nuestros canales de discusión',
    'footer.resources.title': 'Recursos',
    'footer.resources.toolkit': 'Kit de Herramientas para Builders',
    'footer.resources.calendar': 'Calendario de Eventos',
    'footer.resources.learning': 'Ruta de Aprendizaje',
    'footer.resources.coming': 'Próximamente',
    'footer.about.title': 'Nosotras',
    'footer.about.story': 'Nuestra Historia',
    'footer.about.team': 'Equipo',
    'footer.about.press': 'Kit de Prensa',
    'footer.connect.title': 'Conecta',
    'footer.connect.application': 'Formulario de Aplicación',
    'footer.connect.sponsors': 'Información para Patrocinadores',
    'footer.connect.contact': 'Contacto',
    'footer.connect.hot': '¡HOT!',
    'footer.social.title': 'Social',
    'footer.social.twitter.desc': 'Síguenos en X',
    'footer.social.youtube.desc': 'Videos y tutoriales',
    'footer.social.github.desc': 'Explora nuestros proyectos',
    'footer.tagline': 'donde las ideas despiertan',
    'footer.legal.terms': 'Términos',
    'footer.legal.privacy': 'Privacidad',
    'footer.made': 'Hecho con',
    'footer.latam': 'en LATAM',
    'footer.copyright': '© 2025 Buen Día Builders. Construyendo el futuro de Web3 en Latinoamérica.',
  },
  en: {
    // Navbar
    'nav.builders': 'Builders',
    'nav.empresas': 'Companies',
    'nav.blockchains': 'Blockchains',
    'nav.recursos': 'Resources',
    'nav.join': 'Login',
    'nav.dashboard': 'Dashboard',

    // Hero Section  
    'hero.title': 'Connecting Builders, Companies and Blockchains to create Web3\'s future in LATAM',
    'hero.subtitle': 'The space where developers join the construction of Latin America\'s most dynamic Web3 ecosystem.',
    'hero.builder.title': 'I\'m a Builder',
    'hero.builder.subtitle': 'Start your Builder journey',
    'hero.company.title': 'I\'m a Company',
    'hero.company.subtitle': 'Connect with Web3 talent',
    'hero.blockchain.title': 'I\'m a Blockchain',
    'hero.blockchain.subtitle': 'Scale your protocol with BdB',

    // Metrics
    'metrics.builders': 'Active Builders in the System',
    'metrics.companies': 'Connected Companies',
    'metrics.growth': 'Annual Growth of Graduates since 2023',
    'metrics.funding': 'New Assets as Crypto Asset',

    // Main Sections
    'builders.title': 'Connecting builders with ideas and opportunities',
    'builders.description': 'From specialized education, we move to the ecosystem where your professional future can grow, learn and connect with the best opportunities.',
    'builders.cta': 'Become a Builder',
    'companies.title': 'The Web3 talent your company needs',
    'companies.description': 'Specialized recruitment, training and strategic consulting to accelerate your organization\'s Web3 transformation.',
    'companies.cta': 'Hire talent',
    'blockchains.title': 'Accelerate your protocol adoption in LATAM',
    'blockchains.description': 'Technical education, onboarding and community building to expand your ecosystem in the most promising region.',
    'blockchains.cta': 'Expand protocol',

    // Builders Page
    'builders.page.badge': 'Applications Closed',
    'builders.page.title': 'Código Futura 2025',
    'builders.page.subtitle': 'Applications for this edition have successfully closed.',
    'builders.page.thanks': 'Thank you to all the programmers who applied! The program is underway with incredible builders transforming from Web2 to Web3.',
    'builders.stats.title': 'Código Futura 2025 in numbers',
    'builders.stats.subtitle': 'The impact of our first edition',
    'builders.stats.applications': 'Applications received',
    'builders.stats.weeks': 'Training weeks',
    'builders.stats.free': 'Free',
    'builders.stats.scholarships': 'Builder Retreat Scholarships',
    'builders.journey.title': 'The builders journey',
    'builders.journey.subtitle': 'A structured transformation process from Web2 to Web3',
    'builders.journey.application': 'Application',
    'builders.journey.application.title': 'Complete your profile',
    'builders.journey.application.desc': 'Form with your data and social networks',
    'builders.journey.application.duration': '10 min',
    'builders.journey.application.dates': 'Closed',
    'builders.journey.selection': 'Selection',
    'builders.journey.selection.title': 'Technical selection',
    'builders.journey.selection.desc': 'GitHub and/or portfolio review',
    'builders.journey.selection.duration': '1 week',
    'builders.journey.selection.dates': 'October',
    'builders.journey.program': 'Main Program',
    'builders.journey.program.title': 'Código Futura (online, synchronous)',
    'builders.journey.program.desc': 'Classes Tuesday and Thursday 6:30-8:00 PM + Saturday reinforcement. Labs and practical Web3 projects',
    'builders.journey.program.duration': '7 weeks',
    'builders.journey.program.dates': 'Oct 7 - Nov 13',
    'builders.journey.retreat': 'Builder Retreat',
    'builders.journey.retreat.title': 'Builder House (with scholarship, in-person)',
    'builders.journey.retreat.desc': 'Exclusive immersive experience for 20 selected builders who will travel to Buenos Aires, Argentina',
    'builders.journey.retreat.duration': '1 week',
    'builders.journey.retreat.dates': 'Nov 16-23',
    'builders.journey.bootcamp': 'In-Person Bootcamp',
    'builders.journey.bootcamp.title': 'Intensive bootcamp (optional and in-person)',
    'builders.journey.bootcamp.desc': 'Advanced in-person sessions and networking in Buenos Aires, Argentina',
    'builders.journey.bootcamp.duration': '3 days',
    'builders.journey.bootcamp.dates': 'Nov 17-19',
    'builders.journey.hackathon': 'Hackathon',
    'builders.journey.hackathon.title': 'Stellar Hackathon (mandatory and in-person)',
    'builders.journey.hackathon.desc': 'Build your final project and demonstrate everything learned',
    'builders.journey.hackathon.duration': '3 days',
    'builders.journey.hackathon.dates': 'Nov 20-22',
    'builders.journey.graduation': 'Graduation',
    'builders.journey.graduation.title': 'Certification and Portfolio',
    'builders.journey.graduation.desc': 'Official certification and continuous support',
    'builders.journey.graduation.duration': 'Lifetime',
    'builders.journey.graduation.dates': 'Nov 2025',
    'builders.journey.duration.label': 'Duration:',
    'builders.social.title': 'Follow us on social media!',
    'builders.social.subtitle': 'Stay up to date with the current program progress and learn about future calls',
    'builders.social.description': 'Connect with our builder community and be part of the Web3 transformation',
    'builders.future.title': 'Future editions?',
    'builders.future.description': 'We are evaluating upcoming calls. Meanwhile, follow us on social media so you don\'t miss any news.',
    'builders.future.announcement': 'We will announce new dates on our social networks',
    'builders.faq.title': 'Frequently Asked Questions',
    'builders.faq.subtitle': 'Answers about the program and future editions',
    'builders.faq.q1': 'Will there be another edition of the program?',
    'builders.faq.a1': 'We are evaluating future editions. Stay tuned to our social media to learn about news and upcoming calls.',
    'builders.faq.q2': 'Was this program really free?',
    'builders.faq.a2': 'Yes, our training program is completely free for builders. We are funded through B2B services with companies and protocols.',
    'builders.faq.q3': 'What technical level was needed?',
    'builders.faq.a3': 'We were looking for programmers with development experience. No prior knowledge of Web3 was needed, that was taught during the program.',
    'builders.faq.q4': 'What was the class schedule?',
    'builders.faq.a4': 'Classes were Tuesday and Thursday from 6:30 PM to 8:00 PM, plus Saturday reinforcement for 7 weeks (from October 7 to November 13). The final hackathon from November 20-22 is mandatory and in-person.',
    'builders.faq.q5': 'What is the Builder Retreat from November 16-23?',
    'builders.faq.a5': 'It is an immersive one-week experience for 20 selected builders with a scholarship who will travel to Buenos Aires, Argentina. It includes the in-person bootcamp (Nov 17-19) and exclusive networking.',
    'builders.faq.q6': 'How can I stay updated on future editions?',
    'builders.faq.a6': 'Follow us on our social media (Twitter/X, LinkedIn and Instagram) where we announce all the news, calls and program updates.',

    // Companies Page
    'companies.page.badge': 'For Companies',
    'companies.page.title': 'The Web3 talent your company needs',
    'companies.page.subtitle': 'Specialized recruitment, training and strategic consulting to accelerate your organization\'s Web3 transformation',
    'companies.page.cta': 'Schedule a discovery call',
    'companies.process.title': 'Our process',
    'companies.process.subtitle': 'Proven methodology for successful delivery of corporate Web3 projects',
    'companies.process.discovery': 'Discovery Call',
    'companies.process.discovery.desc': 'We understand your specific needs and business context',
    'companies.process.discovery.duration': '1 hour',
    'companies.process.discovery.deliverable': 'Initial diagnosis',
    'companies.process.proposal': 'Customized Proposal',
    'companies.process.proposal.desc': 'We design specific plan with timeline and transparent pricing',
    'companies.process.proposal.duration': '3-5 days',
    'companies.process.proposal.deliverable': 'Detailed proposal',
    'companies.process.execution': 'Execution',
    'companies.process.execution.desc': 'Delivery with clear metrics and constant communication',
    'companies.process.execution.duration': 'Variable',
    'companies.process.execution.deliverable': 'Weekly reports',
    'companies.process.followup': 'Follow-up',
    'companies.process.followup.desc': 'Continuous support and results-based optimization',
    'companies.process.followup.duration': 'Ongoing',
    'companies.process.followup.deliverable': 'Success metrics',
    'companies.talent.title': 'Talents',
    'companies.talent.subtitle': 'Available profiles according to your company needs',
    'companies.talent.junior': 'Junior Builders',
    'companies.talent.junior.desc': 'High motivation, recent training',
    'companies.talent.mid': 'Mid-Level',
    'companies.talent.mid.desc': 'Real projects, practical experience',
    'companies.talent.senior': 'Senior',
    'companies.talent.senior.desc': 'Leadership capability, architecture decisions, mentoring',
    'companies.talent.specialist': 'Specialists',
    'companies.talent.specialist.desc': 'Specific experience in verticals like DeFi, Gaming, Infrastructure',
    'companies.form.title': 'Let\'s start working together',
    'companies.form.subtitle': 'Tell us your needs and we\'ll contact you within 24 hours',
    'companies.form.company': 'Company',
    'companies.form.company.placeholder': 'Your company name',
    'companies.form.name': 'Your name',
    'companies.form.name.placeholder': 'Your full name',
    'companies.form.email': 'Corporate email',
    'companies.form.email.placeholder': 'you@company.com',
    'companies.form.role': 'Your role',
    'companies.form.role.placeholder': 'CTO, HR Director, etc.',
    'companies.form.needs': 'What do you need?',
    'companies.form.needs.placeholder': 'Describe your need: hiring, training, consulting...',
    'companies.form.submit': 'Request discovery call',
    'companies.form.submitting': 'Sending...',

    // Blockchains Page
    'blockchains.page.badge': 'For Blockchains and Protocols',
    'blockchains.page.title': 'Accelerate your protocol adoption in LATAM',
    'blockchains.page.subtitle': 'Technical education, onboarding and community development to expand your ecosystem in the most promising region',
    'blockchains.page.cta': 'Explore our partnerships',
    'blockchains.methodology.title': 'Our approach',
    'blockchains.methodology.subtitle': '4-phase methodology to ensure your expansion success',
    'blockchains.methodology.phase': 'Phase',
    'blockchains.methodology.analysis': 'Deep protocol analysis',
    'blockchains.methodology.analysis.desc': 'We understand your application suite, tokenomics and roadmap.',
    'blockchains.methodology.analysis.duration': '2 weeks',
    'blockchains.methodology.analysis.deliverable': 'Technical analysis',
    'blockchains.methodology.curriculum': 'Curriculum Design',
    'blockchains.methodology.curriculum.desc': 'Customized educational program for your protocol',
    'blockchains.methodology.curriculum.duration': '3 weeks',
    'blockchains.methodology.curriculum.deliverable': 'Custom curriculum',
    'blockchains.methodology.execution': 'Execution & Delivery',
    'blockchains.methodology.execution.desc': 'Training delivery + community building execution',
    'blockchains.methodology.execution.duration': '12-24 weeks',
    'blockchains.methodology.execution.deliverable': 'Trained developers',
    'blockchains.methodology.metrics': 'Metrics & Optimization',
    'blockchains.methodology.metrics.desc': 'KPIs tracking and continuous optimization',
    'blockchains.methodology.metrics.duration': 'Ongoing',
    'blockchains.methodology.metrics.deliverable': 'Performance reports',
    'blockchains.protocols.title': 'Protocols we develop on',
    'blockchains.protocols.subtitle': 'Technical experience across different Web3 ecosystem verticals',
    'blockchains.form.title': 'Let\'s explore our partnership',
    'blockchains.form.subtitle': 'Tell us about your protocol and goals in LATAM',
    'blockchains.form.protocol': 'Protocol/Project',
    'blockchains.form.protocol.placeholder': 'Your protocol name',
    'blockchains.form.name': 'Your name',
    'blockchains.form.name.placeholder': 'Your full name',
    'blockchains.form.email': 'Email',
    'blockchains.form.email.placeholder': 'you@protocol.com',
    'blockchains.form.role': 'Your role',
    'blockchains.form.role.placeholder': 'DevRel, BD, etc.',
    'blockchains.form.goals': 'Goals in LATAM',
    'blockchains.form.goals.placeholder': 'What do you want to achieve in the region? Developer adoption, community growth, partnerships...',
    'blockchains.form.budget': 'Approximate budget (USD)',
    'blockchains.form.budget.placeholder': 'Investment range for the program',
    'blockchains.form.submit': 'Request customized program',
    'blockchains.form.submitting': 'Sending...',

    // Cities Section
    'cities.title': 'Buen día Builders in your city',
    'cities.subtitle': 'Expanding the Web3 ecosystem throughout Latin America, city by city',
    'cities.operating': 'Cities where we operate',
    'cities.active': 'Active',
    'cities.coming': 'Coming soon',
    'cities.form.title': 'Your city is not on the list?',
    'cities.form.description': 'Register and we will contact you when Buen día Builders arrives in your city',
    'cities.form.email.placeholder': 'your@email.com',
    'cities.form.city.placeholder': 'Your city',
    'cities.form.submit': 'Notify me when available',
    'cities.form.disclaimer': 'We will keep you informed about events and opportunities in your region',

    // Footer
    'footer.newsletter.title': 'Stay updated',
    'footer.newsletter.description': 'Receive the latest news from the Web3 ecosystem in LATAM',
    'footer.newsletter.placeholder': 'your@email.com',
    'footer.community.title': 'Community',
    'footer.community.email': 'Send message',
    'footer.community.email.desc': 'Contact us by email',
    'footer.community.linkedin.desc': 'Connect with our professional network',
    'footer.community.telegram.desc': 'Join our conversations',
    'footer.community.discord.desc': 'Join our discussion channels',
    'footer.resources.title': 'Resources',
    'footer.resources.toolkit': 'Builders Toolkit',
    'footer.resources.calendar': 'Events Calendar',
    'footer.resources.learning': 'Learning Path',
    'footer.resources.coming': 'Coming soon',
    'footer.about.title': 'About Us',
    'footer.about.story': 'Our Story',
    'footer.about.team': 'Team',
    'footer.about.press': 'Press Kit',
    'footer.connect.title': 'Connect',
    'footer.connect.application': 'Application Form',
    'footer.connect.sponsors': 'Sponsor Information',
    'footer.connect.contact': 'Contact',
    'footer.connect.hot': 'HOT!',
    'footer.social.title': 'Social',
    'footer.social.twitter.desc': 'Follow us on X',
    'footer.social.youtube.desc': 'Videos and tutorials',
    'footer.social.github.desc': 'Explore our projects',
    'footer.tagline': 'where ideas awaken',
    'footer.legal.terms': 'Terms',
    'footer.legal.privacy': 'Privacy',
    'footer.made': 'Made with',
    'footer.latam': 'in LATAM',
    'footer.copyright': '© 2025 Buen Día Builders. Building the future of Web3 in Latin America.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({
  children,
  defaultLanguage = 'es',
}: {
  children: React.ReactNode;
  defaultLanguage?: Language;
}) {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key
  };

  useEffect(() => {
    const savedLanguage = localStorage.getItem('bdb-language') as Language;
    if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('bdb-language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}